title: "Chinguun Munkhtsetseg"
description: "Genetics & Genomics @ DKU"
baseurl: ""
url: "https://chinguunxo.github.io"

author:
  name: "Chinguun Munkhtsetseg"
  email: "cm720@duke.edu"
  bio: "Hello! I am an undergraduate student and aspiring bioinformatician at Duke Kunshan University, majoring in Genetics and Genomics within the Molecular Biosciences program. I am particularly interested in epigenetics and RNA biology and how they can illuminate women’s health conditions such as endometriosis and ovarian cancer. More specifically, I aim to explore non‑hormonal therapeutic strategies for gynecologic diseases and malignancies, with a focus on improving efficacy while minimizing physical and mental adverse effects."
  location: "Kunshan, Suzhou, China"
  github: "chinguunxo"
  linkedin: "chinguun-m"
  tiktok: "chinguun.xo"

# ── Build settings ──────────────────────────────────────
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
highlighter: rouge

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
